### ISSUE TITLE
Sequelize v4 Support

### ISSUE THREAD

**Issue by ehegnes** [gimenete/sequelize-sync-diff#4]
Are you planning on supporting v4 with this project?

Sequelize v4 does have support for automatically altering tables, but this project has been handy in the past since it allows for a review of commands before execution.

**Comment by gimenete** [comment]
I'm glad this has been a handy project for you :)

Sorry, I'm not maintaining the project. I haven't used sequelize since a long time ago. So I prefer not to have to maintain new versions. Feel free to fork the project.

**Comment by gimenete** [comment]
@ehegnes btw, sequelize now supports `.sync({ alter: true })`
https://github.com/sequelize/sequelize/issues/537
